#!/usr/bin/env python3
"""Generate the SLO dashboards (backlog #177-#181) and splice them into
argocd/apps/grafana.yaml between the generated-block markers.

The deployed source of truth stays grafana.yaml (ArgoCD only watches this
repo, ADR 0003); this script only keeps the dashboards consistent with the
standard in observability/grafana/dashboards/README.md ("SLO dashboards"):
status tiles first, one tile per SLO, the same expression as the alert,
"no data" shown as its own state and never as green.

    scripts/gen-slo-dashboards.py          # rewrite grafana.yaml in place
    scripts/gen-slo-dashboards.py --check  # exit 1 if grafana.yaml is stale
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "argocd/apps/grafana.yaml"

PROV_BEGIN = "              # >>> slo-providers (generated by scripts/gen-slo-dashboards.py)"
PROV_END = "              # <<< slo-providers"
DASH_BEGIN = "          # >>> slo-dashboards (generated by scripts/gen-slo-dashboards.py)"
DASH_END = "          # <<< slo-dashboards"

DS = {"type": "prometheus", "uid": "prometheus"}
GREY = "#6b7280"


# --- the SLO catalogue: one entry per SLO, one tile each -------------------
#
# Every expression is the alert rule's own expression (or, where no alert
# exists, the ADR 0020 SLI) over a fixed 5m window, reduced to ONE series.
# `red` is the breach boundary the tile and the counters share; `amber` is the
# "meeting the target but close" boundary. dir "high": higher is better (red
# below `red`); dir "low": lower is better (red at or above `red`).

def ratio(err, total, w="5m"):
    return f"1 - ((sum(rate({err}[{w}])) or vector(0)) / (sum(rate({total}[{w}])) > 0))"


API_TOTAL = 'http_server_requests_seconds_count{job="api", uri!~"/actuator.*"}'
API_ERR = 'http_server_requests_seconds_count{job="api", outcome="SERVER_ERROR", uri!~"/actuator.*"}'
LK_TOTAL = 'http_server_requests_seconds_count{job="api", uri="/variants/lookup"}'
LK_ERR = 'http_server_requests_seconds_count{job="api", outcome="SERVER_ERROR", uri="/variants/lookup"}'
AGG_TOTAL = 'http_server_requests_seconds_count{job="aggregator", uri=~"/aggregates.*"}'
AGG_ERR = 'http_server_requests_seconds_count{job="aggregator", outcome="SERVER_ERROR", uri=~"/aggregates.*"}'

CLINVAR, MARKET, PLATFORM = "ClinVar variant lookup", "Market-data pipeline", "Platform"

SLOS = [
    # id, section, title, expr, unit, dir, amber, red, description, extra
    dict(id="api-ok", sec=CLINVAR, title="API requests succeeding", unit="percentunit", dir="high", amber=0.99, red=0.95,
         expr=ratio(API_ERR, API_TOTAL), dec=1, nv="No traffic", link="api-golden-signals",
         desc="Share of api requests without a 5xx over 5 minutes. Target 95% (alert ApiHighErrorRate)."),
    dict(id="lookup-ok", sec=CLINVAR, title="Variant lookups succeeding", unit="percentunit", dir="high", amber=0.97, red=0.90,
         expr=ratio(LK_ERR, LK_TOTAL), dec=1, nv="No traffic", link="api-golden-signals",
         desc="Share of GET /variants/lookup calls (the clinvar-service dependency) without a 5xx over 5 minutes. Target 90% (alert ApiVariantsLookupHighErrorRate)."),
    dict(id="api-p95", sec=CLINVAR, title="API response time (p95)", unit="s", dir="low", amber=0.7, red=1.0,
         expr='histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job="api", uri!~"/actuator.*"}[5m])) by (le))',
         dec=2, nv="No traffic", link="api-golden-signals",
         desc="95% of requests finish faster than this. Target under 1 s: the canary's api-slo-check threshold, preliminary (ADR 0020 addendum 2026-08-17); there is no alert on it."),
    dict(id="workers-ok", sec=CLINVAR, title="Workers processing without errors", unit="percentunit", dir="high", amber=0.99, red=0.95,
         expr='1 - ((sum(rate(spring_kafka_listener_seconds_count{job="workers", error!="none"}[5m])) or vector(0)) / (sum(rate(spring_kafka_listener_seconds_count{job="workers"}[5m])) > 0))',
         dec=1, nv="No traffic", link="workers-golden-signals",
         desc="Share of work-items messages handled without an error over 5 minutes. Target 95% (alert WorkersListenerErrorRate)."),
    dict(id="workers-lag", sec=CLINVAR, title="Workers backlog", unit="short", dir="low", amber=100, red=500,
         expr='sum(kafka_consumer_fetch_manager_records_lag{job="workers"})', dec=0, nv="No data", link="workers-golden-signals",
         desc="Messages waiting for the workers. Alert WorkersConsumerLagHigh fires above 500."),
    dict(id="clinvar-fresh", sec=CLINVAR, title="ClinVar data refreshed (last 8 days)", unit="none", dir="high", amber=1, red=1,
         expr='sum(increase(clinvar_ingestion_jobs_total{job="clinvar-service", status="succeeded"}[8d])) >= bool 1',
         kind="bool", on="Fresh", off="Stale", nv="No data", link="clinvar-service-golden-signals",
         desc="Whether a ClinVar ingestion succeeded in the last 8 days (alert ClinVarIngestionFreshnessBreach)."),
    dict(id="dlq", sec=CLINVAR, title="Failed notifications waiting", unit="short", dir="low", amber=0.5, red=0.5,
         expr='sum(watchlist_delivery_dlq_depth{job="watchlist-service"})', kind="zero", zero="None", dec=0, nv="No data",
         link="watchlist-service-golden-signals",
         desc="Watchlist notifications that exhausted their retries. Any value above 0 fires WatchlistDlqDepthHigh."),

    dict(id="feed-live", sec=MARKET, title="Market feed live", unit="none", dir="high", amber=1, red=1,
         expr='1 - max(market_data_stale_feed{job="market-data-ingestor"})', kind="bool", on="Live", off="Stale", nv="No data",
         link="market-data-ingestor-golden-signals",
         desc="Whether market-data-ingestor is receiving ticks when it should (alert MarketDataStaleFeed)."),
    dict(id="news-ok", sec=MARKET, title="News feeds polled OK", unit="percentunit", dir="high", amber=0.99, red=0.90,
         expr='sum(increase(news_ingestor_feed_poll_total{outcome="succeeded"}[1h])) / (sum(increase(news_ingestor_feed_poll_total[1h])) > 0)',
         dec=1, nv="No data", link="news-ingestor-golden-signals",
         desc="Share of feed polls that succeeded in the last hour. ADR 0020 SLI; the 90% bar is preliminary and has no alert."),
    dict(id="sent-ok", sec=MARKET, title="Sentiment scoring without errors", unit="percentunit", dir="high", amber=0.99, red=0.95,
         expr='1 - ((sum(increase(sentiment_analyzer_consume_errors_total[1h])) + sum(increase(sentiment_analyzer_publish_errors_total[1h]))) / (sum(increase(sentiment_analyzer_articles_consumed_total[1h])) > 0))',
         dec=1, nv="No traffic", link="sentiment-analyzer-golden-signals",
         desc="Articles consumed and published without an error in the last hour. ADR 0020 SLI; the 95% bar is preliminary and has no alert."),
    dict(id="sent-lag", sec=MARKET, title="Sentiment backlog", unit="short", dir="low", amber=10, red=20,
         expr='sum(sentiment_analyzer_consumer_lag{job="sentiment-analyzer"})', dec=0, nv="No data",
         link="sentiment-analyzer-golden-signals", desc="Articles waiting to be scored. Alert SentimentAnalyzerConsumerLagHigh fires above 20."),
    dict(id="agg-ok", sec=MARKET, title="Aggregates API succeeding", unit="percentunit", dir="high", amber=0.99, red=0.95,
         expr=ratio(AGG_ERR, AGG_TOTAL), dec=1, nv="No traffic", link="aggregator-golden-signals",
         desc="Share of GET /aggregates calls without a 5xx over 5 minutes. ADR 0020 SLI; the 95% bar is preliminary and has no alert."),
    dict(id="agg-lag", sec=MARKET, title="Aggregator backlog", unit="short", dir="low", amber=10, red=20,
         expr='sum(kafka_consumer_fetch_manager_records_lag{job="aggregator", topic=~"stock\\\\.price\\\\.tick|news\\\\.sentiment\\\\.scored"})',
         dec=0, nv="No data", link="aggregator-golden-signals",
         desc="Records waiting for the aggregator. Alert AggregatorConsumerLagHigh fires above 20."),
    dict(id="fresh", sec=MARKET, title="Price freshness (p95)", unit="s", dir="low", amber=20, red=30,
         expr='histogram_quantile(0.95, sum(rate(aggregator_price_freshness_seconds_bucket{source="WEBSOCKET"}[10m])) by (le))',
         dec=1, nv="No data", link="aggregator-golden-signals",
         desc="How old a real trade is when the pipeline has processed it. Target under 30 s (alert AggregatorPriceFreshnessSlow). Shows No data when the market is closed."),

    dict(id="disk", sec=PLATFORM, title="Node disk free", unit="percentunit", dir="high", amber=0.20, red=0.10,
         expr='min(node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})', dec=0, nv="No data",
         desc="Free space on the node's root filesystem. NodeDiskSpaceLow below 20%, NodeDiskSpaceCritical below 10%."),
    dict(id="kafka", sec=PLATFORM, title="Kafka reachable", unit="none", dir="high", amber=1, red=1,
         expr='min(probe_success{job="blackbox-kafka-tcp"})', kind="bool", on="Up", off="Down", nv="No data",
         desc="Whether the blackbox probe reaches the Kafka broker (alert KafkaBrokerUnavailable)."),
    dict(id="probes", sec=PLATFORM, title="Failing health probes", unit="short", dir="low", amber=0.5, red=0.5,
         expr='count(probe_success{job=~"blackbox-.*", job!="blackbox-kafka-tcp"} == 0) or vector(0)', kind="zero", zero="All OK", dec=0,
         nv="No data", desc="Blackbox probes currently failing (alert BlackboxProbeFailing)."),
    dict(id="argocd", sec=PLATFORM, title="ArgoCD apps out of sync", unit="short", dir="low", amber=0.5, red=0.5,
         expr='count(argocd_app_info{sync_status!="Synced", name!~"clinvar-postgresql|grafana|kafka|postgresql|redis|cilium"}) or vector(0)',
         kind="zero", zero="All synced", dec=0, nv="No data",
         desc="Applications whose live state differs from git (alert ArgoCDAppOutOfSync, same exclusions)."),
    dict(id="backup", sec=PLATFORM, title="Oldest database backup", unit="s", dir="low", amber=93600, red=180000,
         expr='max(time() - kube_cronjob_status_last_successful_time{cronjob=~".*backup.*"})', dec=1, nv="No data",
         desc="Age of the least recent successful nightly backup across the three databases. Amber above 26 h, red above 50 h; preliminary, no alert yet."),
    dict(id="telemetry", sec=PLATFORM, title="Telemetry backends up", unit="none", dir="high", amber=1, red=1,
         expr='min(up{job=~"loki|tempo|pyroscope"})', kind="bool", on="Up", off="Down", nv="No data",
         desc="Loki, Tempo and Pyroscope are being scraped (alert TelemetryBackendDown)."),
    dict(id="restarts", sec=PLATFORM, title="Restarting workloads", unit="short", dir="low", amber=0.5, red=0.5,
         expr='count(increase(kube_pod_container_status_restarts_total[1h]) > 3) or vector(0)', kind="zero", zero="None", dec=0,
         nv="No data", desc="Containers that restarted more than 3 times in the last hour (alert WorkloadRestartingFrequently)."),
    dict(id="targets", sec=PLATFORM, title="Metric targets down", unit="short", dir="low", amber=0.5, red=0.5,
         expr='count(up == 0) or vector(0)', kind="zero", zero="None", dec=0, nv="No data",
         desc="Prometheus scrape targets that are not answering."),
]

GREEN, AMBER, RED, GREY = "green", "#f59e0b", "red", "#6b7280"


def is_ok(s):
    return f"({s['expr']}) < {s['red']}" if s["dir"] == "low" else f"({s['expr']}) >= {s['red']}"


def is_bad(s):
    return f"({s['expr']}) >= {s['red']}" if s["dir"] == "low" else f"({s['expr']}) < {s['red']}"


# Declared SLOs (ADR 0020 addendum 2026-10-10) are NOT tiles: they come from the
# slo:* recording rules (#177) and are shown by slo_table(). What stays in
# SLOS is health and saturation signals, shown on "Service health" (#180).
SLO_TILE_IDS = {"api-ok", "lookup-ok", "api-p95", "workers-ok", "news-ok", "sent-ok", "agg-ok", "fresh"}
PIPELINES, PLATFORM_H = "Pipelines and queues", "Platform"
HEALTH_PIPELINE_IDS = {"workers-lag", "dlq", "clinvar-fresh", "feed-live", "sent-lag", "agg-lag"}
HEALTH = [dict(s, sec=PIPELINES if s["id"] in HEALTH_PIPELINE_IDS else PLATFORM_H)
          for s in SLOS if s["id"] not in SLO_TILE_IDS]


def count_expr(pred, items):
    return " + ".join(f"(count({pred(s)}) or vector(0))" for s in items)


def stat(pid, x, y, w, h, title, expr, unit, steps, desc, *, decimals=None, mappings=None, no_value="No data",
         graph="none", instant=False, link=None, text_mode="value"):
    d = {"unit": unit, "noValue": no_value, "mappings": mappings or [],
         "thresholds": {"mode": "absolute", "steps": [{"color": c, "value": v} for c, v in steps]}}
    if decimals is not None:
        d["decimals"] = decimals
    p = {"id": pid, "type": "stat", "title": title, "description": desc,
         "gridPos": {"x": x, "y": y, "w": w, "h": h}, "datasource": DS,
         "options": {"colorMode": "background", "graphMode": graph, "textMode": text_mode, "justifyMode": "center",
                     "reduceOptions": {"calcs": ["lastNotNull"]}},
         "fieldConfig": {"defaults": d, "overrides": []},
         "targets": [{"refId": "A", "datasource": DS, "expr": expr, "instant": instant}]}
    if link:
        p["links"] = [{"title": "Details (Golden Signals)", "url": f"/d/{link}"}]
    return p


def slo_tile(pid, x, y, s):
    if s["dir"] == "high":
        steps = [(RED, None), (AMBER, s["red"]), (GREEN, s["amber"])]
    else:
        steps = [(GREEN, None), (AMBER, s["amber"]), (RED, s["red"])]
    kind = s.get("kind")
    if kind == "bool":
        maps = [{"type": "value", "options": {"0": {"text": s["off"], "color": RED}, "1": {"text": s["on"], "color": GREEN}}}]
        steps = [(RED, None), (GREEN, 1)]
    elif kind == "zero":
        maps = [{"type": "value", "options": {"0": {"text": s["zero"], "color": GREEN}}}]
    else:
        maps = []
    maps.append({"type": "special", "options": {"match": "null+nan", "result": {"text": s["nv"], "color": GREY}}})
    return stat(pid, x, y, 4, 5, s["title"], s["expr"], s["unit"], steps, s["desc"], decimals=s.get("dec"), mappings=maps,
                no_value=s["nv"], graph="area", link=s.get("link"))


def service_health():
    items = HEALTH
    n = len(items)
    ok, bad = count_expr(is_ok, items), count_expr(is_bad, items)
    legend = ("**Service health, not SLOs.** These are health and saturation signals: queue backlogs, liveness, disk, "
              "backups, sync state. The SLOs (objective, window, error budget) are on the **SLO table** dashboard. "
              "**Green** healthy · **amber** close to its alert · **red** unhealthy · **grey** no data or nothing to "
              "measure. Each tile's description names its alert, or says there is none and the threshold is preliminary. "
              "Click a tile for the detailed dashboard.")
    panels = [
        {"id": 1, "type": "text", "title": "", "transparent": True, "gridPos": {"x": 0, "y": 0, "w": 24, "h": 3},
         "options": {"mode": "markdown", "content": legend}},
        stat(2, 0, 3, 8, 4, f"Signals healthy (of {n})", ok, "none",
             [(RED, None), (AMBER, n - 3), (GREEN, n)], f"How many of the {n} signals below are inside their threshold right now.",
             decimals=0, instant=True),
        stat(3, 8, 3, 8, 4, "Signals unhealthy", bad, "none", [(GREEN, None), (RED, 1)],
             "Signals outside their threshold. Look at these first.", decimals=0, instant=True),
        stat(4, 16, 3, 8, 4, "No data", f"{n} - ({ok}) - ({bad})", "none", [(GREEN, None), (GREY, 1)],
             "Signals with nothing to measure right now (for example the market is closed). Not a problem by itself.",
             decimals=0, instant=True),
    ]
    pid, y = 10, 7
    for sec in (PIPELINES, PLATFORM_H):
        sec_items = [s for s in items if s["sec"] == sec]
        panels.append({"id": pid, "type": "row", "title": sec, "collapsed": False, "panels": [],
                       "gridPos": {"x": 0, "y": y, "w": 24, "h": 1}})
        pid += 1
        y += 1
        for i, s in enumerate(sec_items):
            panels.append(slo_tile(pid, (i % 6) * 4, y + (i // 6) * 5, s))
            pid += 1
        y += ((len(sec_items) - 1) // 6 + 1) * 5
    return {"uid": "service-health", "title": "Service health", "tags": ["health"], "timezone": "browser",
            "schemaVersion": 39, "version": 1, "editable": False, "graphTooltip": 1,
            "time": {"from": "now-6h", "to": "now"}, "refresh": "30s", "panels": panels,
            "description": "Health and saturation signals that are not SLOs."}


# --- the SLO table (#178): reads ONLY slo:* recording rules ------------------

# Declared in ADR 0020's 2026-10-10 addendum but not measurable today, and what unblocks each.
DORMANT = [
    ("variants-lookup", "no requests in 6 days", "#183 synthetic traffic"),
    ("clinvar-lookup", "the metric has no status label", "#21e"),
    ("clinvar-ingestion-freshness", "time-based, needs a last-success gauge", "#184"),
    ("workers-listener", "workers does not export the listener metric, so its alert cannot fire", "#185"),
    ("watchlist-delivery", "no delivery attempts in 6 days", "none yet"),
]


def table_query(ref, expr):
    return {"refId": ref, "datasource": DS, "expr": expr, "instant": True, "format": "table"}


def slo_table():
    pt = lambda ref, name, unit, dec, extra=None: {
        "matcher": {"id": "byName", "options": name},
        "properties": [{"id": "unit", "value": unit}, {"id": "decimals", "value": dec}] + (extra or [])}
    status_map = [{"type": "value", "options": {
        "0": {"text": "Breached", "color": "red"}, "1": {"text": "At risk", "color": "#f59e0b"},
        "2": {"text": "Met", "color": "green"}}},
        {"type": "special", "options": {"match": "null+nan", "result": {"text": "Insufficient events", "color": GREY}}}]
    cell_bg = {"id": "custom.cellOptions", "value": {"type": "color-background"}}
    budget_colors = {"id": "thresholds", "value": {"mode": "absolute", "steps": [
        {"color": "red", "value": None}, {"color": "#f59e0b", "value": 0}, {"color": "green", "value": 0.25}]}}
    table = {
        "id": 10, "type": "table", "title": "Declared SLOs: objective, 7-day window, error budget",
        "description": "One row per declared SLO (ADR 0020 addendum, 2026-10-10). All columns read the slo:* recording rules. "
                       "Compliance = good / valid events over the window. Budget remaining = 1 - (1 - compliance) / (1 - objective). "
                       "Status: Breached below 0, At risk below 25%, otherwise Met. An SLO with too few events shows Insufficient events.",
        "gridPos": {"x": 0, "y": 6, "w": 24, "h": 9}, "datasource": DS,
        "targets": [table_query("A", "slo:objective:ratio"), table_query("B", "slo:valid:increase7d"),
                    table_query("C", "slo:compliance:ratio7d"), table_query("D", "slo:error_budget_remaining:ratio7d"),
                    table_query("E", "(slo:error_budget_remaining:ratio7d >= bool 0.25) + (slo:error_budget_remaining:ratio7d >= bool 0)")],
        "transformations": [
            {"id": "joinByField", "options": {"byField": "slo", "mode": "outer"}},
            {"id": "organize", "options": {
                "excludeByName": {"Time": True, "Time 1": True, "Time 2": True, "Time 3": True, "Time 4": True, "Time 5": True,
                                  "__name__": True, "service": True, "service 1": True, "service 2": True, "service 3": True,
                                  "service 4": True, "service 5": True},
                "renameByName": {"slo": "SLO", "Value #A": "Objective", "Value #B": "Events in window", "Value #C": "Compliance",
                                 "Value #D": "Budget remaining", "Value #E": "Status"},
                "indexByName": {"SLO": 0, "Objective": 1, "Events in window": 2, "Compliance": 3, "Budget remaining": 4, "Status": 5}}},
            {"id": "sortBy", "options": {"sort": [{"field": "SLO"}]}}],
        "options": {"showHeader": True, "cellHeight": "md"},
        "fieldConfig": {"defaults": {"custom": {"align": "left"}}, "overrides": [
            pt("Objective", "Objective", "percentunit", 2),
            pt("Events in window", "Events in window", "short", 0),
            pt("Compliance", "Compliance", "percentunit", 3),
            pt("Budget remaining", "Budget remaining", "percentunit", 1, [cell_bg, budget_colors]),
            {"matcher": {"id": "byName", "options": "Status"},
             "properties": [{"id": "mappings", "value": status_map}, cell_bg,
                            {"id": "thresholds", "value": {"mode": "absolute", "steps": [{"color": GREY, "value": None}]}}]}]},
    }
    kinds = [("SLOs measured", "count(slo:valid:increase7d)", [(GREY, None), (GREEN, 1)], "Declared SLOs with events in the window."),
             ("Met", "count(slo:error_budget_remaining:ratio7d >= 0.25) or vector(0)", [(GREY, None), (GREEN, 1)],
              "Error budget remaining is 25% or more."),
             ("At risk", "count((slo:error_budget_remaining:ratio7d >= 0) < 0.25) or vector(0)", [(GREEN, None), (AMBER, 1)],
              "Budget remaining is below 25% but not exhausted."),
             ("Breached", "count(slo:error_budget_remaining:ratio7d < 0) or vector(0)", [(GREEN, None), (RED, 1)],
              "Error budget exhausted: the SLO is not being met over the window."),
             ("Insufficient events", "count(slo:valid:increase7d) - count(slo:error_budget_remaining:ratio7d)", [(GREEN, None), (GREY, 1)],
              "Too few events in the window to compute compliance. Not a failure.")]
    panels = [
        {"id": 1, "type": "text", "title": "", "transparent": True, "gridPos": {"x": 0, "y": 0, "w": 24, "h": 2},
         "options": {"mode": "markdown", "content":
                     "**An SLO is an indicator (good / valid events), an objective and a window.** Window: rolling 7 days "
                     "(history starts 2026-10-03; the 28-day window is shown from about 2026-10-31). Objectives, definitions and "
                     "the dormant SLOs are in the ADR 0020 addendum of 2026-10-10."}}]
    for i, (t, e, steps, d) in enumerate(kinds):
        x = [0, 5, 10, 14, 19][i]
        w = [5, 5, 4, 5, 5][i]
        panels.append(stat(2 + i, x, 2, w, 4, t, e, "none", steps, d, decimals=0, instant=True))
    panels.append(table)
    rows = "\n".join(f"| `{n}` | {why} | {fix} |" for n, why, fix in DORMANT)
    panels.append({"id": 11, "type": "text", "title": "Declared but not measurable yet (dormant)", "gridPos": {"x": 0, "y": 15, "w": 24, "h": 7},
                   "options": {"mode": "markdown", "content":
                               "These SLOs are declared in the ADR but cannot be computed today.\n\n| SLO | Why | Unblocked by |\n|---|---|---|\n" + rows}})
    return {"uid": "slo-table", "title": "SLOs", "tags": ["slo"], "timezone": "browser", "schemaVersion": 39,
            "version": 1, "editable": False, "graphTooltip": 1, "time": {"from": "now-6h", "to": "now"},
            "refresh": "1m", "panels": panels, "description": "Declared SLOs with objective, window and error budget."}


# --- informative overviews (#186): what is running, how loaded, how connected ---
#
# Plain information panels, not status: gauges, stats, tables and trend lines.
# Timeseries panels are kept minimal on purpose (unit + legend only, the same
# shape as the Golden Signals dashboards): the first SLO dashboard's styled
# timeseries rendered empty and the cause was never found.

def gauge(pid, x, y, w, h, title, expr, unit, steps, desc, mx=None, dec=0):
    d = {"unit": unit, "decimals": dec, "min": 0, "noValue": "No data",
         "thresholds": {"mode": "absolute", "steps": [{"color": c, "value": v} for c, v in steps]}}
    if mx is not None:
        d["max"] = mx
    return {"id": pid, "type": "gauge", "title": title, "description": desc, "gridPos": {"x": x, "y": y, "w": w, "h": h},
            "datasource": DS, "options": {"reduceOptions": {"calcs": ["lastNotNull"]}, "showThresholdMarkers": True},
            "fieldConfig": {"defaults": d, "overrides": []},
            "targets": [{"refId": "A", "datasource": DS, "expr": expr, "instant": True}]}


def info_stat(pid, x, y, w, h, title, expr, unit, desc, dec=None, steps=None):
    """A neutral number (blue) unless thresholds are given."""
    return stat(pid, x, y, w, h, title, expr, unit, steps or [("#3b82f6", None)], desc, decimals=dec, instant=True)


def ts(pid, x, y, w, title, series, unit, desc, h=8):
    return {"id": pid, "type": "timeseries", "title": title, "description": desc, "gridPos": {"x": x, "y": y, "w": w, "h": h},
            "datasource": DS, "fieldConfig": {"defaults": {"unit": unit}, "overrides": []},
            "targets": [{"refId": chr(65 + i), "datasource": DS, "expr": e, "legendFormat": l} for i, (e, l) in enumerate(series)]}


def header(text_md, h=2):
    return {"id": 1, "type": "text", "title": "", "transparent": True, "gridPos": {"x": 0, "y": 0, "w": 24, "h": h},
            "options": {"mode": "markdown", "content": text_md}}


def row(pid, y, title):
    return {"id": pid, "type": "row", "title": title, "collapsed": False, "panels": [], "gridPos": {"x": 0, "y": y, "w": 24, "h": 1}}


def dash(uid, title, tags, panels, desc):
    return {"uid": uid, "title": title, "tags": tags, "timezone": "browser", "schemaVersion": 39, "version": 1, "editable": False,
            "graphTooltip": 1, "time": {"from": "now-6h", "to": "now"}, "refresh": "30s", "panels": panels, "description": desc}


GA = [(GREEN, None), (AMBER, 70), (RED, 90)]
NODE_CPU = '100 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100'
NODE_MEM = '(1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)) * 100'
NODE_DISK = '(1 - min(node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100'


def infrastructure_overview():
    P = [header("**The node and the platform around it**: one machine (Ryzen 7 8845HS, 58 GiB RAM, 1 TB NVMe) on a USB Wi-Fi "
                "link, running k3s, Cilium, ArgoCD and the observability stack. Gauges turn amber at 70% and red at 90%. "
                "SLOs are on the **SLOs** dashboard and pass/fail signals on **Service health**.")]
    P += [gauge(2, 0, 2, 4, 5, "CPU busy", NODE_CPU, "percent", GA, "Average CPU use across all cores, 5-minute rate.", 100),
          gauge(3, 4, 2, 4, 5, "Memory used", NODE_MEM, "percent", GA, "Memory in use (total minus available), host-wide.", 100),
          gauge(4, 8, 2, 4, 5, "Disk used (/)", NODE_DISK, "percent", [(GREEN, None), (AMBER, 80), (RED, 90)],
                "Used share of the root filesystem. Alerts fire below 20% and 10% free.", 100),
          info_stat(5, 12, 2, 4, 5, "Load (1 min)", "node_load1", "none", "Run-queue load average; the host has 16 threads.", 2),
          info_stat(6, 16, 2, 4, 5, "Uptime", "time() - node_boot_time_seconds", "s", "Time since the host last booted."),
          info_stat(7, 20, 2, 4, 5, "Pods running (limit 110)", 'sum(kube_pod_status_phase{phase="Running"})', "none",
                    "Running pods on the node; the kubelet limit is 110.", 0)]
    P += [row(10, 7, "Load over time"),
          ts(11, 0, 8, 12, "CPU busy %", [(NODE_CPU, "CPU busy")], "percent", "Host CPU use."),
          ts(12, 12, 8, 12, "Memory used %", [(NODE_MEM, "memory used"),
                                              ('(1 - sum(node_memory_SwapFree_bytes) / sum(node_memory_SwapTotal_bytes)) * 100', "swap used")],
             "percent", "Host memory and swap use."),
          row(13, 16, "Network: the Wi-Fi link"),
          ts(14, 0, 17, 8, "Wi-Fi throughput", [('sum(rate(node_network_receive_bytes_total{device=~"wl.*"}[5m]))', "download"),
                                                 ('sum(rate(node_network_transmit_bytes_total{device=~"wl.*"}[5m]))', "upload")],
             "Bps", "Bytes per second over the wireless interfaces."),
          ts(15, 8, 17, 8, "Link drops (carrier changes per hour)", [('sum(changes(node_network_carrier{device=~"wl.*"}[1h]))', "carrier changes")],
             "none", "How often the Wi-Fi link lost or regained carrier. The control plane tolerates this poorly (backlog #162)."),
          ts(16, 16, 17, 8, "Disk I/O", [('sum(rate(node_disk_read_bytes_total[5m]))', "read"), ('sum(rate(node_disk_written_bytes_total[5m]))', "write")],
             "Bps", "Bytes per second read from and written to disk."),
          row(17, 25, "Kubernetes and GitOps"),
          ts(18, 0, 26, 12, "Running pods per namespace", [('sum by (namespace)(kube_pod_status_phase{phase="Running"})', "{{namespace}}")],
             "none", "Where the pods live."),
          info_stat(19, 12, 26, 3, 4, "Apps synced", 'count(argocd_app_info{sync_status="Synced"}) or vector(0)', "none", "ArgoCD applications whose live state matches git.", 0),
          info_stat(20, 15, 26, 3, 4, "Apps out of sync", 'count(argocd_app_info{sync_status!="Synced"}) or vector(0)', "none",
                    "ArgoCD applications that differ from git (some are manual-sync by design).", 0, [(GREEN, None), (AMBER, 1)]),
          info_stat(21, 18, 26, 3, 4, "Apps healthy", 'count(argocd_app_info{health_status="Healthy"}) or vector(0)', "none", "ArgoCD applications reporting Healthy.", 0),
          info_stat(22, 21, 26, 3, 4, "Apps not healthy", 'count(argocd_app_info{health_status!="Healthy"}) or vector(0)', "none",
                    "ArgoCD applications Degraded, Progressing or Missing.", 0, [(GREEN, None), (AMBER, 1)]),
          info_stat(23, 12, 30, 4, 4, "Certificates: days to first expiry", "min((certmanager_certificate_expiration_timestamp_seconds - time()) / 86400)",
                    "none", "Soonest expiry among cert-manager certificates.", 0, [(RED, None), (AMBER, 14), (GREEN, 30)]),
          info_stat(24, 16, 30, 4, 4, "Ingress requests/s", "sum(rate(traefik_entrypoint_requests_total[5m]))", "reqps", "Requests through Traefik.", 2),
          info_stat(25, 20, 30, 4, 4, "Metric series (Prometheus)", "prometheus_tsdb_head_series", "short", "Active time series in the Prometheus head.", 0),
          ts(26, 0, 34, 12, "Pod restarts per hour", [('sum(increase(kube_pod_container_status_restarts_total[1h]))', "all workloads")],
             "none", "Container restarts across the cluster."),
          ts(27, 12, 34, 12, "Kubernetes API requests/s", [('sum(rate(apiserver_request_total[5m]))', "API server")],
             "reqps", "Requests served by the k3s API server.")]
    return dash("infrastructure-overview", "Infrastructure overview", ["overview", "infrastructure"], P,
                "The node and the platform: load, memory, disk, network, pods and GitOps.")


def services_overview():
    ns = lambda e: f"sum by (namespace)({e})"
    tq = lambda ref, e: table_query(ref, e)
    table = {
        "id": 20, "type": "table", "title": "Every namespace at a glance",
        "description": "One row per namespace: running pods, restarts in the last 24 hours, CPU, memory, and memory as a share of its limits.",
        "gridPos": {"x": 0, "y": 6, "w": 24, "h": 11}, "datasource": DS,
        "targets": [tq("A", ns('kube_pod_status_phase{phase="Running"}')),
                    tq("B", ns('round(increase(kube_pod_container_status_restarts_total[24h]))')),
                    tq("C", ns('rate(container_cpu_usage_seconds_total{container!=""}[5m])')),
                    tq("D", ns('container_memory_working_set_bytes{container!=""}')),
                    tq("E", ns('container_memory_working_set_bytes{container!=""}') + ' / ' + ns('kube_pod_container_resource_limits{resource="memory"}'))],
        "transformations": [
            {"id": "joinByField", "options": {"byField": "namespace", "mode": "outer"}},
            {"id": "organize", "options": {
                "excludeByName": {f"Time{suf}": True for suf in ["", " 1", " 2", " 3", " 4", " 5"]},
                "renameByName": {"namespace": "Namespace", "Value #A": "Pods running", "Value #B": "Restarts (24h)", "Value #C": "CPU (cores)",
                                 "Value #D": "Memory", "Value #E": "Memory of limits"},
                "indexByName": {"Namespace": 0, "Pods running": 1, "Restarts (24h)": 2, "CPU (cores)": 3, "Memory": 4, "Memory of limits": 5}}},
            {"id": "sortBy", "options": {"sort": [{"field": "Memory", "desc": True}]}}],
        "options": {"showHeader": True, "cellHeight": "sm"},
        "fieldConfig": {"defaults": {"custom": {"align": "left"}}, "overrides": [
            {"matcher": {"id": "byName", "options": "Pods running"}, "properties": [{"id": "unit", "value": "none"}, {"id": "decimals", "value": 0}]},
            {"matcher": {"id": "byName", "options": "Restarts (24h)"}, "properties": [
                {"id": "unit", "value": "none"}, {"id": "decimals", "value": 0},
                {"id": "custom.cellOptions", "value": {"type": "color-text"}},
                {"id": "thresholds", "value": {"mode": "absolute", "steps": [{"color": "green", "value": None}, {"color": "#f59e0b", "value": 1}, {"color": "red", "value": 5}]}}]},
            {"matcher": {"id": "byName", "options": "CPU (cores)"}, "properties": [{"id": "unit", "value": "none"}, {"id": "decimals", "value": 2}]},
            {"matcher": {"id": "byName", "options": "Memory"}, "properties": [{"id": "unit", "value": "bytes"}, {"id": "decimals", "value": 0}]},
            {"matcher": {"id": "byName", "options": "Memory of limits"}, "properties": [
                {"id": "unit", "value": "percentunit"}, {"id": "decimals", "value": 0},
                {"id": "custom.cellOptions", "value": {"type": "gauge", "mode": "basic"}}, {"id": "max", "value": 1}, {"id": "min", "value": 0},
                {"id": "thresholds", "value": {"mode": "absolute", "steps": [{"color": "green", "value": None}, {"color": "#f59e0b", "value": 0.7}, {"color": "red", "value": 0.9}]}}]}]}}
    HTTP = 'http_server_requests_seconds_count{uri!~"/actuator.*"}'
    P = [header("**What is running and how it is behaving**, across the application services and the platform namespaces. "
                "Request metrics cover the services that expose them (api, aggregator, watchlist-service, ...). "
                "SLOs are on the **SLOs** dashboard and pass/fail signals on **Service health**.")]
    P += [info_stat(2, 0, 2, 4, 4, "Pods running", 'sum(kube_pod_status_phase{phase="Running"})', "none", "Pods in the Running phase.", 0),
          info_stat(3, 4, 2, 4, 4, "Running but not ready",
                    'count((kube_pod_status_ready{condition="false"} == 1) and on(namespace,pod) (kube_pod_status_phase{phase="Running"} == 1)) or vector(0)',
                    "none", "Pods that are Running but failing their readiness check.", 0, [(GREEN, None), (RED, 1)]),
          info_stat(4, 8, 2, 4, 4, "Deployments not fully available",
                    "count(kube_deployment_status_replicas_available < kube_deployment_spec_replicas) or vector(0)", "none",
                    "Deployments with fewer ready replicas than desired.", 0, [(GREEN, None), (RED, 1)]),
          info_stat(5, 12, 2, 4, 4, "Restarts (24 h)", "sum(increase(kube_pod_container_status_restarts_total[24h]))", "none",
                    "Container restarts across the cluster in the last 24 hours.", 0, [(GREEN, None), (AMBER, 1), (RED, 10)]),
          info_stat(6, 16, 2, 4, 4, "Requests/s (services)", f"sum(rate({HTTP}[5m]))", "reqps", "HTTP requests handled by all services, actuator excluded.", 2),
          info_stat(7, 20, 2, 4, 4, "Server errors/s", f'sum(rate(http_server_requests_seconds_count{{outcome="SERVER_ERROR"}}[5m])) or vector(0)',
                    "reqps", "5xx responses per second across the services.", 3, [(GREEN, None), (RED, 0.0001)]),
          table,
          row(30, 17, "Traffic"),
          ts(31, 0, 18, 12, "Requests per second, by service", [(f"sum by (job)(rate({HTTP}[5m]))", "{{job}}")], "reqps", "HTTP request rate per service."),
          ts(32, 12, 18, 12, "Response time p95, by service",
             [('histogram_quantile(0.95, sum by (job, le)(rate(http_server_requests_seconds_bucket{uri!~"/actuator.*"}[5m])))', "{{job}}")],
             "s", "95% of requests finish faster than this."),
          row(33, 26, "Resources"),
          ts(34, 0, 27, 12, "CPU by namespace (cores)", [('topk(8, sum by (namespace)(rate(container_cpu_usage_seconds_total{container!=""}[5m])))', "{{namespace}}")],
             "none", "The eight namespaces using the most CPU."),
          ts(35, 12, 27, 12, "Memory by namespace", [('topk(8, sum by (namespace)(container_memory_working_set_bytes{container!=""}))', "{{namespace}}")],
             "bytes", "The eight namespaces using the most memory."),
          ts(36, 0, 35, 12, "JVM heap by service", [('sum by (job)(jvm_memory_used_bytes{area="heap"})', "{{job}}")], "bytes", "Heap in use per JVM service."),
          ts(37, 12, 35, 12, "Kafka consumer lag", [('sum by (job)(kafka_consumer_fetch_manager_records_lag)', "{{job}}")], "none",
             "Messages waiting per consuming service.")]
    return dash("services-overview", "Services overview", ["overview", "services"], P,
                "What is running and how it behaves: pods, restarts, traffic, resources.")


# folder title -> {dashboard key: builder}; one Grafana provider per set
SETS = {"slo": ("SLO", {"slo-table": slo_table}),
        "health": ("Service health", {"service-health": service_health}),
        "overview": ("Overview", {"services-overview": services_overview, "infrastructure-overview": infrastructure_overview})}


def render_block():
    out = [DASH_BEGIN]
    for set_key, (_, dashes) in SETS.items():
        out.append(f"          {set_key}:")
        for key, fn in dashes.items():
            out.append(f"            {key}:")
            out.append("              json: |")
            for line in json.dumps(fn(), indent=2).split("\n"):
                out.append("                " + line)
    out.append(DASH_END)
    return "\n".join(out)


def render_provider():
    out = [PROV_BEGIN]
    for set_key, (folder, _) in SETS.items():
        out += [f"              - name: {set_key}", "                orgId: 1", f"                folder: '{folder}'",
                "                type: file", "                disableDeletion: false", "                editable: false",
                "                options:", f"                  path: /var/lib/grafana/dashboards/{set_key}"]
    out.append(PROV_END)
    return "\n".join(out)


def splice(src, begin, end, block, anchor):
    if begin in src:
        a, b = src.index(begin), src.index(end) + len(end)
        return src[:a] + block + src[b:]
    if anchor not in src:
        sys.exit(f"anchor not found: {anchor!r}")
    return src.replace(anchor, block + "\n" + anchor, 1)


def main():
    src = TARGET.read_text()
    new = splice(src, PROV_BEGIN, PROV_END, render_provider(),
                 "        dashboards:\n          golden-signals:")
    # providers block sits right before `dashboards:`; keep the list contiguous
    new = splice(new, DASH_BEGIN, DASH_END, render_block(), "  destination:\n    server:")
    if "--check" in sys.argv:
        if new != src:
            sys.exit("grafana.yaml is stale: run scripts/gen-slo-dashboards.py")
        return
    TARGET.write_text(new)


if __name__ == "__main__":
    main()
