#!/usr/bin/env python3
"""Generate the SLO dashboards (backlog #177-#181) and splice them into
argocd/apps/grafana.yaml between the generated-block markers.

The deployed source of truth stays grafana.yaml (ArgoCD only watches this
repo, ADR 0003); this script only keeps the dashboards consistent with the
standard in observability/grafana/dashboards/README.md ("SLO dashboards"):
status tiles first, one tile per SLO, the same expression as the alert,
"no data" shown as its own state and never as green.

    scripts/gen-slo-dashboards.py          # rewrite grafana.yaml in place
    scripts/gen-slo-dashboards.py --check  # exit 1 if grafana.yaml is stale
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGET = ROOT / "argocd/apps/grafana.yaml"

PROV_BEGIN = "              # >>> slo-providers (generated by scripts/gen-slo-dashboards.py)"
PROV_END = "              # <<< slo-providers"
DASH_BEGIN = "          # >>> slo-dashboards (generated by scripts/gen-slo-dashboards.py)"
DASH_END = "          # <<< slo-dashboards"

DS = {"type": "prometheus", "uid": "prometheus"}
GREY = "#6b7280"


# --- panel helpers: every SLO dashboard is built from these -----------------

def text(pid, x, y, w, h, md):
    return {"id": pid, "type": "text", "title": "", "gridPos": {"x": x, "y": y, "w": w, "h": h},
            "options": {"mode": "markdown", "content": md}, "transparent": True}


def tile(pid, x, y, title, expr, unit, steps, desc, decimals=None, mappings=None, no_value="No data"):
    """A big status tile: coloured background, value, nothing else."""
    d = {"unit": unit, "noValue": no_value,
         "thresholds": {"mode": "absolute", "steps": [{"color": c, "value": v} for c, v in steps]},
         "mappings": mappings or []}
    if decimals is not None:
        d["decimals"] = decimals
    return {
        "id": pid, "type": "stat", "title": title, "description": desc,
        "gridPos": {"x": x, "y": y, "w": 6, "h": 6}, "datasource": DS,
        "options": {"colorMode": "background", "graphMode": "none", "textMode": "value",
                    "justifyMode": "center", "reduceOptions": {"calcs": ["lastNotNull"]}},
        "fieldConfig": {"defaults": d, "overrides": []},
        "targets": [{"refId": "A", "datasource": DS, "expr": expr, "instant": True}],
    }


def no_traffic():
    # NaN/empty (no requests in the window) is its own grey state, never green.
    return [{"type": "special", "options": {"match": "null+nan",
                                             "result": {"text": "No traffic", "color": GREY}}}]


def trend(pid, x, y, title, expr, unit, desc, line=None, legend="", w=8):
    d = {"unit": unit, "custom": {"lineWidth": 2, "fillOpacity": 12, "showPoints": "never"}}
    if line is not None:
        d["custom"]["thresholdsStyle"] = {"mode": "line"}
        d["thresholds"] = {"mode": "absolute", "steps": [{"color": "transparent", "value": None},
                                                           {"color": "red", "value": line}]}
    return {
        "id": pid, "type": "timeseries", "title": title, "description": desc,
        "gridPos": {"x": x, "y": y, "w": w, "h": 8}, "datasource": DS,
        "options": {"legend": {"displayMode": "hidden"}, "tooltip": {"mode": "single"}},
        "fieldConfig": {"defaults": d, "overrides": []},
        "targets": [{"refId": "A", "datasource": DS, "expr": expr, "legendFormat": legend}],
    }


def dashboard(uid, title, tags, panels, links):
    return {"uid": uid, "title": title, "tags": ["slo"] + tags, "timezone": "browser",
            "schemaVersion": 39, "version": 1, "editable": False, "graphTooltip": 1,
            "time": {"from": "now-6h", "to": "now"}, "refresh": "30s", "panels": panels,
            "links": [{"title": t, "type": "link", "url": u, "icon": "dashboard"} for t, u in links]}


GREEN_AMBER_RED_HIGH_IS_GOOD = lambda red_below, amber_below: [
    ("red", None), ("#f59e0b", red_below), ("green", amber_below)]


# --- api: the reference dashboard (#177) ------------------------------------

API_TOTAL = 'http_server_requests_seconds_count{job="api", uri!~"/actuator.*"}'
API_ERR = 'http_server_requests_seconds_count{job="api", outcome="SERVER_ERROR", uri!~"/actuator.*"}'
LOOKUP_TOTAL = 'http_server_requests_seconds_count{job="api", uri="/variants/lookup"}'
LOOKUP_ERR = 'http_server_requests_seconds_count{job="api", outcome="SERVER_ERROR", uri="/variants/lookup"}'
API_BUCKET = 'http_server_requests_seconds_bucket{job="api", uri!~"/actuator.*"}'


def ratio(err, total, window):
    # The same shape as the alert rules: errors over total, empty when there is no traffic.
    return f"1 - ((sum(rate({err}[{window}])) or vector(0)) / (sum(rate({total}[{window}])) > 0))"


def api_dashboard():
    intro = ("## api: is it meeting its targets?\n"
             "Green means inside the target, amber means close, red means breached, grey means "
             "no traffic or no data. Targets come from ADR 0020: at least 95% of requests succeed, "
             "at least 90% on `GET /variants/lookup`, and p95 latency under 1 s (the canary's "
             "preliminary threshold, ADR 0020 addendum 2026-08-17). Tiles use a 5-minute window, "
             "the same as the alerts.")
    panels = [
        text(1, 0, 0, 24, 3, intro),
        tile(2, 0, 3, "Is api running?", 'min(up{job="api"})', "none",
             [("red", None), ("green", 1)], "1 when every api pod is being scraped, 0 when any is not.",
             mappings=[{"type": "value", "options": {"0": {"text": "Down", "color": "red"},
                                                      "1": {"text": "Running", "color": "green"}}}]),
        tile(3, 6, 3, "Requests succeeding", ratio(API_ERR, API_TOTAL, "5m"), "percentunit",
             GREEN_AMBER_RED_HIGH_IS_GOOD(0.95, 0.99),
             "Share of requests that did not return a 5xx over 5 minutes. Target 95% (alert ApiHighErrorRate).",
             decimals=1, mappings=no_traffic(), no_value="No traffic"),
        tile(4, 12, 3, "Variant lookups succeeding", ratio(LOOKUP_ERR, LOOKUP_TOTAL, "5m"), "percentunit",
             GREEN_AMBER_RED_HIGH_IS_GOOD(0.90, 0.97),
             "Share of GET /variants/lookup calls (the clinvar-service dependency) that did not return a 5xx over 5 minutes. Target 90% (alert ApiVariantsLookupHighErrorRate).",
             decimals=1, mappings=no_traffic(), no_value="No traffic"),
        tile(5, 18, 3, "Typical slow request (p95)",
             f"histogram_quantile(0.95, sum(rate({API_BUCKET}[5m])) by (le))", "s",
             [("green", None), ("#f59e0b", 0.7), ("red", 1)],
             "95% of requests finish faster than this, over 5 minutes. Target under 1 s (the canary's api-slo-check threshold; no alert).",
             decimals=2, mappings=no_traffic(), no_value="No traffic"),
        trend(6, 0, 9, "Success rate over time", ratio(API_ERR, API_TOTAL, "$__rate_interval"), "percentunit",
              "Requests that did not return a 5xx.", legend="success"),
        trend(7, 8, 9, "Slow-request time (p95) over time",
              f"histogram_quantile(0.95, sum(rate({API_BUCKET}[$__rate_interval])) by (le))", "s",
              "p95 request duration. The red line is the 1 s target.", line=1, legend="p95"),
        trend(8, 16, 9, "Traffic", f"sum(rate({API_TOTAL}[$__rate_interval]))", "reqps",
              "Requests per second, actuator endpoints excluded.", legend="requests/s"),
    ]
    return dashboard("slo-api", "SLO: api", ["api"], panels,
                     [("api details (Golden Signals)", "/d/api-golden-signals")])


DASHBOARDS = {"slo-api": api_dashboard}


# --- splice into grafana.yaml ------------------------------------------------

def render_block():
    out = [DASH_BEGIN, "          slo:"]
    for key, fn in DASHBOARDS.items():
        out.append(f"            {key}:")
        out.append("              json: |")
        for line in json.dumps(fn(), indent=2).split("\n"):
            out.append("                " + line)
    out.append(DASH_END)
    return "\n".join(out)


def render_provider():
    return "\n".join([
        PROV_BEGIN,
        "              - name: slo",
        "                orgId: 1",
        "                folder: 'SLO'",
        "                type: file",
        "                disableDeletion: false",
        "                editable: false",
        "                options:",
        "                  path: /var/lib/grafana/dashboards/slo",
        PROV_END])


def splice(src, begin, end, block, anchor):
    if begin in src:
        a, b = src.index(begin), src.index(end) + len(end)
        return src[:a] + block + src[b:]
    if anchor not in src:
        sys.exit(f"anchor not found: {anchor!r}")
    return src.replace(anchor, block + "\n" + anchor, 1)


def main():
    src = TARGET.read_text()
    new = splice(src, PROV_BEGIN, PROV_END, render_provider(),
                 "        dashboards:\n          golden-signals:")
    # providers block sits right before `dashboards:`; keep the list contiguous
    new = splice(new, DASH_BEGIN, DASH_END, render_block(), "  destination:\n    server:")
    if "--check" in sys.argv:
        if new != src:
            sys.exit("grafana.yaml is stale: run scripts/gen-slo-dashboards.py")
        return
    TARGET.write_text(new)


if __name__ == "__main__":
    main()
